newPRWelcomeComment: "Congrats on submitting your first Pull Request here! :tada:  :tada: \nYour PR would be reviewed by a maintainer soon :heavy_check_mark: \nIn the meantime, :star: star this repo and check out our [Instagram](https://www.instagram.com/tle.mec/) page if you wanna learn more about CP & DSA! :smiley:" 

  