name: Greetings

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: "Congrats on submitting your first Pull Request here! :tada:  :tada: \nYour PR would be reviewed by a maintainer soon :heavy_check_mark: \nIn the meantime, :star: star this repo and check out our [Instagram](https://www.instagram.com/tle.mec/) page if you wanna learn more about CP & DSA! :smiley:" 
